# https://circleci.com/developer/images/image/cimg/rust
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.68.2
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
